apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basketdata-claim
  namespace: toytrucks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
