apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
  namespace: toytrucks
spec:
  selector:
    app: catalogapi-pod
  ports:
    - name: "bingo"
      port: 14000
      targetPort: 80
      protocol: TCP
