apiVersion: v1
kind: Service
metadata:
  name: orderapi-service
  namespace: toytrucks
spec:
  selector:
    app: orderapi-pod
  ports:
    - name: "bingo3"
      port: 14004
      targetPort: 80
      protocol: TCP
